title = 'Hugo Lightning'
theme = 'hugo-lightning'
themesdir = '../..'

languageCode = 'en-US'
enableRobotsTXT = true

# lightning = Lightning Theme
[params.lightning.side.home]
taxonomies = ['tags','series']
countTaxonomy = 3

[taxonomies]
tag = 'tags'
topic = 'topics'
series = 'series'

[params.author]
name = 'Matheus Queiroz'

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 1

[[menus.main]]
name = 'Features'
pageRef = '/features'
weight = 2

[[menus.main]]
name = 'About'
pageRef = '/about.md'
weight = 3

# build search index ================
[outputFormats]
 [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[mediaTypes]
 [mediaTypes."application/json"]
  suffixes = ["json"]

[outputs]
 home = ["HTML","RSS", "SearchIndex"]
# ===================================
